# Generated by Django 4.1.7 on 2023-04-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0002_alter_measurement_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="measurement",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="measurement",
            unique_together={("name",)},
        ),
    ]
