# Generated by Django 4.1.7 on 2023-04-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
    ]
