version: "3.9"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: "grocify-backend:${TAG}"
        ports:
            - 8000:8000
    frontend:
        build:
            context: ./frontend
            target: development
        image: "grocify-frontend:${TAG}"
        ports:
            - 3000:3000
