version: "3.9"

services:
    backend:
        build:
            context: ./backend
            target: development
            dockerfile: Dockerfile
        image: "grocify-backend:${TAG}"
        ports:
            - 8000:8000
    
    db:
        image: postgres:15
        env_file:
            - ./backend/.env
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data

    frontend:
        build:
            context: ./frontend
            target: development
        image: "grocify-frontend:${TAG}"
        ports:
            - 3000:3000

volumes:
  pg_data:
