version: "3.9"

services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/backend
        ports:
            - 8000:8000
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/frontend
        ports:
            - 3000:3000
