version: "3.9"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: "us-west2-docker.pkg.dev/grocify-379719/grocify/backend:${TAG}"
        ports:
            - 8000:8000
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: "us-west2-docker.pkg.dev/grocify-379719/grocify/frontend:${TAG}"
        ports:
            - 3000:3000
