# Generated by Django 4.1.7 on 2023-04-23 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_category_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="ingredient",
        ),
    ]
