# Generated by Django 4.1.7 on 2023-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredient_categories", "0001_initial"),
        ("ingredients", "0004_alter_ingredient_name"),
        ("categories", "0003_remove_category_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ingredient",
            field=models.ManyToManyField(
                through="ingredient_categories.IngredientCategory",
                to="ingredients.ingredient",
            ),
        ),
    ]
