# Generated by Django 4.1.7 on 2023-04-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_ingredients'),
        ('recipe_tags', '0001_initial'),
        ('tags', '0002_tags_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='recipes',
            field=models.ManyToManyField(through='recipe_tags.RecipeTag', to='recipes.recipe'),
        ),
    ]
