# Generated by Django 4.1.7 on 2023-04-25 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0004_alter_tags_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="tags",
            unique_together={("name", "user")},
        ),
    ]
