# Generated by Django 4.1.7 on 2023-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredients', '0001_initial'),
        ('ingredients', '0003_remove_ingredient_recipes'),
        ('recipes', '0002_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe_ingredients.RecipeIngredient', to='ingredients.ingredient'),
        ),
    ]
