# Generated by Django 4.1.7 on 2023-04-25 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0004_alter_recipe_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together={("title", "user")},
        ),
    ]
